### ISSUE TITLE
Food Security question

### ISSUE THREAD

**Issue by only1chunts** [FAIRsharing/subject-ontology#31]
Hi, 
There is no definition of Food Security(c_10967) nor of Agricultural Economics and Sociology (SRAO_0000155) so its hard to be sure, but could these be linked in some way? is it possible they are actually the same thing? or is Food Security also a child of Agricultural Economics and Sociology ?
Currently the only place in the ontology that Food Security appears is within the Humanities and not in the Life or natural sciences section.
Thanks
Chris

**Comment by Drosophilic** [comment]
Thanks @only1chunts, we'll look into this. We are working through adding links and definitions. Do you have any other suggestions for definitions and relationships?

**Comment by only1chunts** [comment]
I'm just working through trying to thin it down to a generic slim ontology, so if I spot anything else I'll let you know. I think ~100 terms will be more than enough for my needs.

**Comment by Drosophilic** [comment]
OK, thanks. Let us know if you want to have a call about this.

**Comment by allysonlister** [comment]
Good morning @Drosophilic and @only1chunts - Just to add a little more information, if it helps provide some context. Food Security does have a definition, as provided by AgroVoc, whose term we import. This was added last year via #1. 

'Agricultural Economics and Sociology' is a candidate term for refactoring as it is a composite term (see #19), and this is likely to change with the next point release. It is most likely to change in the development version of the ontology either this week or next week, and therefore if you have any suggestions, do let us know. AgroVoc already provides a class describing Agricultural Economics (see http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/page/c_8672 for details), though there are only near matches for Agricultural Sociology - the nearest is http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/page/c_28827, which would not be a candidate for SRAO.

**Comment by allysonlister** [comment]
Pete and I have discussed this yesterday. We have refactored 'Agricultural Economics and Sociology' to 'Agricultural Economics' with IRI http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/page/c_8672, provided a definition and linked it as a parent term to 'Food Security'. 

We currently see this subject as primarily an economic issue, however as Food Security is now a child of Agricultural Economics, that brings it into the Agriculture hierarchy, which is a child of the Life Sciences. We are therefore closing the ticket. If you have further suggestions or comments on this issue @only1chunts , please feel free to reopen it. Thank you for the ticket!

Please note that these changes are reflected in the development version of the ontology at this time. SRAO is undergoing significant improvements for the next point release (0.2.0), of which this issue is part. For more information on the progress of this milestone, please click on the milestone link in this ticket. If you wish to view the edits so far, you will need to view the development version of the owl file found within https://github.com/FAIRsharing/subject-ontology/tree/master/development - please let us know if you have any questions about accessing it.
