### ISSUE TITLE
Medical specialisms

### ISSUE THREAD

**Issue by Drosophilic** [FAIRsharing/subject-ontology#49]
We need to add more medical specialisms, such as Respiratory Disease, Rheumatism, etc., particularly in light of the new resources appearing due to the Coronavirus pandemic.

**Comment by allysonlister** [comment]
Some searching on the interwebs has resulting in the following we may or may not choose to add to SRAO (I've included @Drosophilic's suggestions in this list too):

1. Medical Virology / Clinical Virology
2. Infectious Diseases (this is often listed online as a specialism in its own right, but I think it might also be redundant with our existing term "Epidemiology"?
3. Respiratory Disease
4. Rheumatism: We do already have 'Rheumatology' in SRAO. If you would also like 'Rheumatism', I suggest we add it to DRAO?

Any others? Once I have a yes or no for each of these, I'll give the "Yes" terms their own ticket, and will link to this overall ticket.

FYI other specialisms associated with this subject area that are *already* in SRAO (and which I double checked as I was looking for new terms to add to SRAO) are:

1. Medical Microbiology
2. Public Health
3. Epidemiology
4. Molecular Infection Biology (also get people using the term Infection Biology, but not sure we need that as a synonym)
5. Tropical Diseases

**Comment by Drosophilic** [comment]
Hi @allysonlister,
In response to your questions:
1. Medical Virology / Clinical Virology

We already have the term 'Virology' so I'm not sure about the value of adding a child term 'Medical Virology' to both this term and, I assume 'Medicine'? 

In addition, Clinical Virology seems a subset of Medical Virology. Were you thinking to have this as a child term of Medical Virology?

2. Infectious Diseases (this is often listed online as a specialism in its own right, but I think it might also be redundant with our existing term "Epidemiology"?

Epidemiology and Infectious Diseases seem different topics to me. Epidemiology, as I understand it, is about the health and the spread of disease through a population, whereas Infectious Diseases is about the disease itself and it's progression in an individual (as opposed to a population. 

I would therefore suggest Infectious Diseases should be a separate term. The next question is where then should it fall, in SRAO or DRAO?

3. Respiratory Disease

Yes, I think we should add this.

Rheumatism: We do already have 'Rheumatology' in SRAO. If you would also like 'Rheumatism', I suggest we add it to DRAO?

Aah, I didn't find it for some reason. I don't think we should add Rheumatism to DRAO.

**Comment by allysonlister** [comment]
> 
>  1.   Medical Virology / Clinical Virology
> 
> We already have the term 'Virology' so I'm not sure about the value of adding a child term 'Medical Virology' to both this term and, I assume 'Medicine'?
> 
> In addition, Clinical Virology seems a subset of Medical Virology. Were you thinking to have this as a child term of Medical Virology?

Virology is in the purely microbiology sense in SRAO at the moment (definition "Study of viruses, e.g. sequence and structural data, interactions of viral proteins, or a viral genome including molecular sequences, genes and annotation."), and Microbiology is it's only parent term. I was wondering if we also needed a research area that had some clinical/medical aspects as well. WRT clinical versus medical, I was imaging them to perhaps be synonyms.


  

> 2.  Infectious Diseases (this is often listed online as a specialism in its own right, but I think it might also be redundant with our existing term "Epidemiology"?
> 
> Epidemiology and Infectious Diseases seem different topics to me. Epidemiology, as I understand it, is about the health and the spread of disease through a population, whereas Infectious Diseases is about the disease itself and it's progression in an individual (as opposed to a population.
> 
> I would therefore suggest Infectious Diseases should be a separate term. The next question is where then should it fall, in SRAO or DRAO?
> 

I'll have a think and post again tomorrow :)

As for numbers 3 and 4, I'm happy to proceed with these as you suggest. I will create the appropriate tickets and proceed tomorrow.

thanks :)

**Comment by allysonlister** [comment]
> 
>  1.   Medical Virology / Clinical Virology
> 
> We already have the term 'Virology' so I'm not sure about the value of adding a child term 'Medical Virology' to both this term and, I assume 'Medicine'?
> 
> In addition, Clinical Virology seems a subset of Medical Virology. Were you thinking to have this as a child term of Medical Virology?

Virology is in the purely microbiology sense in SRAO at the moment (definition "Study of viruses, e.g. sequence and structural data, interactions of viral proteins, or a viral genome including molecular sequences, genes and annotation."), and Microbiology is it's only parent term. I was wondering if we also needed a research area that had some clinical/medical aspects as well. WRT clinical versus medical, I was imaging them to perhaps be synonyms.


  

> 2.  Infectious Diseases (this is often listed online as a specialism in its own right, but I think it might also be redundant with our existing term "Epidemiology"?
> 
> Epidemiology and Infectious Diseases seem different topics to me. Epidemiology, as I understand it, is about the health and the spread of disease through a population, whereas Infectious Diseases is about the disease itself and it's progression in an individual (as opposed to a population.
> 
> I would therefore suggest Infectious Diseases should be a separate term. The next question is where then should it fall, in SRAO or DRAO?
> 

I'll have a think and get back to you later today :) (I actually thought I had posted this yesterday aft, but it seems I didn't press the Comment button!)

As for numbers 3 and 4, I'm happy to proceed with these as you suggest. I will create the appropriate tickets and proceed later today.

thanks :)

**Comment by delphinedauga** [comment]
> > 1. Medical Virology / Clinical Virology
> > 
> > We already have the term 'Virology' so I'm not sure about the value of adding a child term 'Medical Virology' to both this term and, I assume 'Medicine'?
> > In addition, Clinical Virology seems a subset of Medical Virology. Were you thinking to have this as a child term of Medical Virology?
> 
> Virology is in the purely microbiology sense in SRAO at the moment (definition "Study of viruses, e.g. sequence and structural data, interactions of viral proteins, or a viral genome including molecular sequences, genes and annotation."), and Microbiology is it's only parent term. I was wondering if we also needed a research area that had some clinical/medical aspects as well. WRT clinical versus medical, I was imaging them to perhaps be synonyms.
> 

I agree with Ally
- « Medical virology » could be used as the same model as « medical microbiology » (The study of microorganisms with an emphasis on their role in the human disease process) : The study of virus with an emphasis on their role in the human disease process.

I found 1 definition for « clinical virology » : 
- A subdiscipline of virology focusing on aspects of human virology that directly pertains to virus-induced clinical conditions, including epidemiology, pathogenesis, diagnosis and detection, and prevention and treatment (National Cancer Institute Thesaurus (NCIT))

Quite difficult to me to make a difference between « medical » & « clinical » and I think the definition below is wrong.
- Clinical : Relating to the examination and treatment of patients dependent on direct observation. The term may also refer to the institution (clinic) providing this activity (National Cancer Institute Thesaurus (NCIT))
- Medical : Relating to the study or practice of medicine (National Cancer Institute Thesaurus (NCIT))

« Clinical » is more specific compared to « medical ». I would use « medical virology » instead of « clinical virology », because « medical virology » will include the examination and treatment of patients dependent on direct observation but also potential treatment studies and prevention.

**Comment by Drosophilic** [comment]
For 'Medical/Clinical Virology', the dilemma for me is that we have the term 'Virology' and we can identify when this is to do with humans by the Homo sapiens taxonomy term, so having Medical/Clinical virology seems a bit repetitive and I worry that we will end up with inconsistencies in curation, outside of SRAO/DRAO (as an aside, I don't think we should necessarily be creating human-specific instances of other disciplines).

I agree Delphine, Clinical is more specific than Medical, but if we are to have a further Virology term, I think I currently would prefer Clinical Virology. It should have parents in both the Medicine and Virology lineages. Perhaps we could discuss edge cases like this in a quick call at some point.

**Comment by allysonlister** [comment]
Happy to have a quick call sometime this week. Was interesting reading your comments guys, and I do understand about the curation issue of having more terms but not knowing about them. IIRC the new system will have better ways to traverse the hierarchies of the ontologies while curating records, so that hopefully if we start typing Virology we should see the near neighbors and choose appropriately (not sure if it's in the MVP but I remember talking about it with the devs at our last workshop). Also, while I get your point about it possibly affecting curation, if we think it appropriate to model something like Medical/Clinical Virology, then a curation limitation shouldn't stop us from having it.

I also agree about cross-referencing the species with the SRAO term in records so that you don't need to have the few human-specific instances of disciplines, but again, would SRAO always be used together with taxonomy info? Looking to the future of the ontology, that is... 

I don't feel we have to have these terms, but I am enjoying working through the options with you both :)

**Comment by allysonlister** [comment]
> Epidemiology and Infectious Diseases seem different topics to me. Epidemiology, as I understand it, is about the health and the spread of disease through a population, whereas Infectious Diseases is about the disease itself and it's progression in an individual (as opposed to a population.
> 
> I would therefore suggest Infectious Diseases should be a separate term. The next question is where then should it fall, in SRAO or DRAO?

After thinking about this for a bit, unless we can come up with a subject area that correctly encompasses Infectious Disease (and I can't think of one, even after some google searching), I think it might belong in DRAO. 

https://www.nature.com/subjects/infectious-diseases says "Infectious diseases, also known as contagious diseases, transmissible diseases or communicable diseases, are caused by pathogenic microorganisms that infect a host organism and can be spread, directly or indirectly, from one organism to another. "

To me this matches our other disease types already in DRAO. There are a [number of pre-existing classes](https://www.ebi.ac.uk/ols/search?q=infectious+disease) that we could use, which if we all agree I can investigate which is best within DRAO based on other disease terms we've already used.

**Comment by Drosophilic** [comment]
I was thinking about 'Infectious Diseases' too. Perhaps this should go under 'Disease'-->'Human Disease' in DRAO? Alternatively, it could be 'Infectology' and go under Medicine. We could then consider adding 'Medical/Clinical Virology' as a child term.

For Respiratory Disease, I would suggest this goes under Medicine as 'Respiratory Medicine'.

**Comment by allysonlister** [comment]
Thanks @Drosophilic - I can see both ways, but I'm starting to lean towards DRAO, though I would have thought that 'Infectious Disease' would be appropriate for non-humans too?

EFO, OBI and IDO have infectious disease as a child term of disease; IDO uses the OGMS disease term (as we do) and OBI and EFO each use their own IRI disease term, but the structure is the same.  Although all classes would be appropriate, as we are already using many EFO terms for various children of the disease class, and [EFO has the best definition and equivalentTo crossreferences to other ontologies](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005741).

Further, if we go this way, we should place our 'malaria' term as a child of infectious disease.

**Comment by allysonlister** [comment]
After discussion with @delphinedauga  and @Drosophilic, we have decided to add Medical Virology (with parents Virology and Medicine), and a near synonym of Clinical Virology. Please note that the new FAIRsharing system does not yet know about near synonyms, only exact synonyms.

**Comment by allysonlister** [comment]
@Drosophilic I made notes on everything we talked about except for Infectious Disease. Do you recall if we decided to go the SRAO or DRAO route on this one? In relation to #52, I think I recall we decided to have a speciality that mimics what we decided for Respiratory Medicine, something like Infectious Disease Medicine. 

I also remember us discussing that this didn't preclude us also having a DRAO term for the disease process. Shall I progress with both terms?

**Comment by Drosophilic** [comment]
Hi Ally, I can confirm we said 'Infectious Disease Medicine' for the SRAO term, and then we chose 'Infectology' for DRAO.

**Comment by allysonlister** [comment]
Fantastic - thanks!

**Comment by allysonlister** [comment]
All items in this ticket have now been resolved.
